In [186]:
import pandas as pd
import numpy as np
from sklearn import tree
import graphviz
import math

In [165]:
hr_data_train = pd.read_csv("ibm_data_train.csv")
hr_data_test = pd.read_csv("ibm_data_test.csv")

hr_data_train

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7
10,35,No,Travel_Rarely,809,Research & Development,16,3,Medical,1,14,...,3,80,1,6,5,3,5,4,0,3
11,29,No,Travel_Rarely,153,Research & Development,15,2,Life Sciences,1,15,...,4,80,0,10,3,3,9,5,0,8
12,31,No,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,16,...,4,80,1,5,1,2,5,2,4,3
13,34,No,Travel_Rarely,1346,Research & Development,19,2,Medical,1,18,...,3,80,1,3,2,3,2,2,1,2
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
15,29,No,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,1,20,...,3,80,1,10,1,3,10,9,8,8
16,32,No,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,...,4,80,2,7,5,2,6,2,0,5
17,22,No,Non-Travel,1123,Research & Development,16,2,Medical,1,22,...,2,80,2,1,2,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
19,38,No,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,...,3,80,0,6,3,3,3,2,1,2
20,24,No,Non-Travel,673,Research & Development,11,2,Other,1,26,...,4,80,1,5,5,2,4,2,1,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
22,34,No,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,...,3,80,0,13,4,3,12,6,2,11
23,21,No,Travel_Rarely,391,Research & Development,15,2,Life Sciences,1,30,...,4,80,0,0,6,3,0,0,0,0
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
27,42,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,...,4,80,1,10,2,3,9,7,4,2
28,44,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,...,4,80,1,24,4,3,22,6,5,17
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1270,34,No,Travel_Rarely,511,Sales,3,2,Life Sciences,1,1779,...,1,80,0,6,3,3,2,2,2,2
1271,21,Yes,Travel_Rarely,337,Sales,7,1,Marketing,1,1780,...,2,80,0,1,3,3,1,0,1,0
1272,38,No,Travel_Rarely,1153,Research & Development,6,2,Other,1,1782,...,2,80,1,5,3,3,5,4,0,4
1273,22,Yes,Travel_Rarely,1294,Research & Development,8,1,Medical,1,1783,...,3,80,0,1,6,3,1,0,0,0
1274,31,No,Travel_Rarely,196,Sales,29,4,Marketing,1,1784,...,1,80,2,13,3,3,12,7,5,7
1275,51,No,Travel_Rarely,942,Research & Development,3,3,Technical Degree,1,1786,...,4,80,0,15,2,3,2,2,2,2
1276,37,No,Travel_Rarely,589,Sales,9,2,Marketing,1,1787,...,1,80,2,5,2,3,5,2,0,3
1277,46,No,Travel_Rarely,734,Research & Development,2,4,Medical,1,1789,...,3,80,1,24,3,3,2,1,2,2
1278,36,No,Travel_Rarely,1383,Research & Development,10,3,Life Sciences,1,1790,...,4,80,1,15,1,3,12,8,5,7
1279,44,Yes,Travel_Frequently,429,Research & Development,1,2,Medical,1,1792,...,3,80,3,6,2,2,5,3,2,3
1280,37,No,Travel_Rarely,1239,Human Resources,8,2,Other,1,1794,...,3,80,0,19,4,2,10,0,4,7
1281,35,Yes,Travel_Rarely,303,Sales,27,3,Life Sciences,1,1797,...,4,80,0,10,2,3,10,7,7,7
1282,33,No,Travel_Rarely,867,Research & Development,8,4,Life Sciences,1,1798,...,2,80,1,14,1,3,10,8,7,6
1283,28,No,Travel_Rarely,1181,Research & Development,1,3,Life Sciences,1,1799,...,3,80,1,5,6,4,5,3,0,3
1284,39,No,Travel_Rarely,1253,Research & Development,10,1,Medical,1,1800,...,3,80,0,9,3,3,4,3,2,2
1285,46,No,Non-Travel,849,Sales,26,2,Life Sciences,1,1801,...,3,80,0,6,3,3,2,2,2,2
1286,40,No,Travel_Rarely,616,Research & Development,2,2,Life Sciences,1,1802,...,4,80,1,7,5,2,4,3,0,2
1287,42,No,Travel_Rarely,1128,Research & Development,13,3,Medical,1,1803,...,3,80,2,10,2,2,0,0,0,0
1288,35,No,Non-Travel,1180,Research & Development,2,2,Medical,1,1804,...,3,80,1,15,6,3,7,7,1,7
1289,38,No,Non-Travel,1336,Human Resources,2,3,Human Resources,1,1805,...,4,80,3,13,3,3,11,10,3,8
1290,34,Yes,Travel_Frequently,234,Research & Development,9,4,Life Sciences,1,1807,...,3,80,1,11,3,2,7,1,0,7
1291,37,Yes,Travel_Rarely,370,Research & Development,10,4,Medical,1,1809,...,2,80,0,10,4,1,10,3,0,8
1292,39,No,Travel_Frequently,766,Sales,20,3,Life Sciences,1,1812,...,4,80,1,7,6,3,2,1,2,2
1293,43,No,Non-Travel,343,Research & Development,9,3,Life Sciences,1,1813,...,3,80,0,7,2,2,3,2,1,2
1294,41,No,Travel_Rarely,447,Research & Development,5,3,Life Sciences,1,1814,...,1,80,0,11,3,1,3,2,1,2
1295,41,No,Travel_Rarely,796,Sales,4,1,Marketing,1,1815,...,4,80,1,23,3,4,22,14,13,5
1296,30,No,Travel_Rarely,1092,Research & Development,10,3,Medical,1,1816,...,2,80,0,9,3,3,7,7,0,2
1297,26,Yes,Travel_Rarely,920,Human Resources,20,2,Medical,1,1818,...,3,80,0,6,3,3,5,1,1,4
1298,46,Yes,Travel_Rarely,261,Research & Development,21,2,Medical,1,1821,...,4,80,1,13,2,4,9,7,3,7
1299,40,No,Travel_Rarely,1194,Research & Development,1,3,Life Sciences,1,1822,...,4,80,1,12,3,3,5,3,0,3

In [250]:
MAX_DEPTH = 6
hr_regressor = tree.DecisionTreeRegressor(max_depth=MAX_DEPTH)

In [251]:
#X_trainを作る
X_train = pd.DataFrame()

#数字のカラムのいみ残す
for i,item in hr_data_train.iteritems():
    if type(item[0]) == np.int64:
        #X_train = pd.concat([X_train, item], axis=1)
        X_train[i] = item

#TotalWorkingYearsを除く
X_train = X_train.drop(["TotalWorkingYears"], axis=1)

X_train

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,3,1,80,0,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,4,80,1,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,3,2,80,0,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,3,80,0,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,3,4,80,1,3,3,2,2,2,2
5,32,1005,2,2,1,8,4,79,3,1,...,3,3,80,0,2,2,7,7,3,6
6,59,1324,3,3,1,10,3,81,4,1,...,4,1,80,3,3,2,1,0,0,0
7,30,1358,24,1,1,11,4,67,3,1,...,4,2,80,1,2,3,1,0,0,0
8,38,216,23,3,1,12,4,44,2,3,...,4,2,80,0,2,3,9,7,1,8
9,36,1299,27,3,1,13,3,94,3,2,...,3,2,80,2,3,2,7,7,7,7
10,35,809,16,3,1,14,1,84,4,1,...,3,3,80,1,5,3,5,4,0,3
11,29,153,15,2,1,15,4,49,2,2,...,3,4,80,0,3,3,9,5,0,8
12,31,670,26,1,1,16,1,31,3,1,...,3,4,80,1,1,2,5,2,4,3
13,34,1346,19,2,1,18,2,93,3,1,...,3,3,80,1,2,3,2,2,1,2
14,28,103,24,3,1,19,3,50,2,1,...,3,2,80,0,4,3,4,2,0,3
15,29,1389,21,4,1,20,2,51,4,3,...,3,3,80,1,1,3,10,9,8,8
16,32,334,5,2,1,21,1,80,4,1,...,3,4,80,2,5,2,6,2,0,5
17,22,1123,16,2,1,22,4,96,4,1,...,3,2,80,2,2,2,1,0,0,0
18,53,1219,2,4,1,23,1,78,2,4,...,3,3,80,0,3,3,25,8,3,7
19,38,371,2,3,1,24,4,45,3,1,...,3,3,80,0,3,3,3,2,1,2
20,24,673,11,2,1,26,1,96,4,2,...,3,4,80,1,5,2,4,2,1,3
21,36,1218,9,4,1,27,3,82,2,1,...,4,2,80,0,4,3,5,3,0,3
22,34,419,7,4,1,28,1,53,3,3,...,3,3,80,0,4,3,12,6,2,11
23,21,391,15,2,1,30,3,96,3,1,...,3,4,80,0,6,3,0,0,0,0
24,34,699,6,1,1,31,2,83,3,1,...,3,3,80,0,2,3,4,2,1,3
25,53,1282,5,3,1,32,3,58,3,5,...,3,4,80,1,3,2,14,13,4,8
26,32,1125,16,1,1,33,2,72,1,1,...,4,2,80,0,5,3,10,2,6,7
27,42,691,8,4,1,35,3,48,3,2,...,3,4,80,1,2,3,9,7,4,2
28,44,477,7,4,1,36,1,42,2,3,...,3,4,80,1,4,3,22,6,5,17
29,46,705,2,4,1,38,2,83,3,5,...,3,4,80,0,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1270,34,511,3,2,1,1779,4,32,1,2,...,3,1,80,0,3,3,2,2,2,2
1271,21,337,7,1,1,1780,2,31,3,1,...,3,2,80,0,3,3,1,0,1,0
1272,38,1153,6,2,1,1782,4,40,2,1,...,3,2,80,1,3,3,5,4,0,4
1273,22,1294,8,1,1,1783,3,79,3,1,...,3,3,80,0,6,3,1,0,0,0
1274,31,196,29,4,1,1784,1,91,2,2,...,3,1,80,2,3,3,12,7,5,7
1275,51,942,3,3,1,1786,1,53,3,3,...,3,4,80,0,2,3,2,2,2,2
1276,37,589,9,2,1,1787,2,46,2,2,...,3,1,80,2,2,3,5,2,0,3
1277,46,734,2,4,1,1789,3,46,3,5,...,3,3,80,1,3,3,2,1,2,2
1278,36,1383,10,3,1,1790,4,90,3,3,...,3,4,80,1,1,3,12,8,5,7
1279,44,429,1,2,1,1792,3,99,3,1,...,3,3,80,3,2,2,5,3,2,3
1280,37,1239,8,2,1,1794,3,89,3,2,...,3,3,80,0,4,2,10,0,4,7
1281,35,303,27,3,1,1797,3,84,3,2,...,3,4,80,0,2,3,10,7,7,7
1282,33,867,8,4,1,1798,4,90,4,1,...,3,2,80,1,1,3,10,8,7,6
1283,28,1181,1,3,1,1799,3,82,3,1,...,3,3,80,1,6,4,5,3,0,3
1284,39,1253,10,1,1,1800,3,65,3,3,...,4,3,80,0,3,3,4,3,2,2
1285,46,849,26,2,1,1801,2,98,2,2,...,3,3,80,0,3,3,2,2,2,2
1286,40,616,2,2,1,1802,3,99,3,1,...,3,4,80,1,5,2,4,3,0,2
1287,42,1128,13,3,1,1803,2,95,4,2,...,3,3,80,2,2,2,0,0,0,0
1288,35,1180,2,2,1,1804,2,90,3,2,...,3,3,80,1,6,3,7,7,1,7
1289,38,1336,2,3,1,1805,1,100,3,1,...,3,4,80,3,3,3,11,10,3,8
1290,34,234,9,4,1,1807,4,93,3,2,...,3,3,80,1,3,2,7,1,0,7
1291,37,370,10,4,1,1809,4,58,3,2,...,3,2,80,0,4,1,10,3,0,8
1292,39,766,20,3,1,1812,3,83,3,2,...,3,4,80,1,6,3,2,1,2,2
1293,43,343,9,3,1,1813,1,52,3,1,...,3,3,80,0,2,2,3,2,1,2
1294,41,447,5,3,1,1814,2,85,4,2,...,3,1,80,0,3,1,3,2,1,2
1295,41,796,4,1,1,1815,3,81,3,3,...,3,4,80,1,3,4,22,14,13,5
1296,30,1092,10,3,1,1816,1,64,3,3,...,3,2,80,0,3,3,7,7,0,2
1297,26,920,20,2,1,1818,4,69,3,1,...,3,3,80,0,3,3,5,1,1,4
1298,46,261,21,2,1,1821,4,66,3,2,...,4,4,80,1,2,4,9,7,3,7
1299,40,1194,1,3,1,1822,3,52,3,2,...,3,4,80,1,3,3,5,3,0,3

In [252]:
#y_trainを作成
y_train = hr_data_train["TotalWorkingYears"]

In [253]:
#学習する
#yは教師データ、
#行列は大文字で書く、ベクトルは小文字で書く
#予測したいものはtarget(y、一次元のベクトル、小文字で書く)と呼ぶ、予測に使うデータはfeature(X、行列で大文字で書く)と呼ぶ
hr_regressor.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=6, max_features=None,
           max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [254]:
#testのセットを作成する
#X_testを作る
X_test = pd.DataFrame()

#数字のカラムのいみ残す
for i,item in hr_data_test.iteritems():
    if type(item[0]) == np.int64:
        X_test[i] = item

#TotalWorkingYearsを除く
X_test = X_test.drop(["TotalWorkingYears"], axis=1)

X_test

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,34,810,8,2,1,1823,2,92,4,2,...,4,3,80,2,5,3,10,8,4,8
1,58,350,2,3,1,1824,2,52,3,4,...,4,4,80,1,0,2,16,9,14,14
2,35,185,23,4,1,1826,2,91,1,1,...,3,2,80,1,2,4,5,4,0,3
3,47,1001,4,3,1,1827,3,92,2,3,...,3,3,80,1,4,3,22,11,14,10
4,40,750,12,3,1,1829,2,47,3,2,...,3,2,80,1,3,3,7,4,7,7
5,54,431,7,4,1,1830,4,68,3,2,...,3,2,80,1,2,2,7,1,1,7
6,31,1125,7,4,1,1833,1,68,3,3,...,3,4,80,2,3,3,3,2,2,2
7,28,1217,1,3,1,1834,3,67,3,1,...,4,3,80,1,3,3,3,2,1,2
8,38,723,2,4,1,1835,2,77,1,2,...,4,1,80,2,4,2,4,2,0,3
9,26,572,10,3,1,1836,3,46,3,2,...,3,1,80,0,4,3,5,3,1,2
10,58,1216,15,4,1,1837,1,87,3,4,...,3,2,80,0,3,3,2,2,2,2
11,18,1431,14,3,1,1839,2,33,3,1,...,3,3,80,0,4,1,0,0,0,0
12,31,359,18,5,1,1842,4,89,4,1,...,3,3,80,0,4,3,1,0,0,0
13,29,350,13,3,1,1844,1,56,2,1,...,3,4,80,3,3,3,2,2,2,0
14,45,589,2,4,1,1845,3,67,3,2,...,4,2,80,2,3,4,8,7,5,7
15,36,430,2,4,1,1847,4,73,3,2,...,4,4,80,1,2,3,1,0,0,0
16,43,1422,2,4,1,1849,1,92,3,2,...,4,3,80,1,5,3,7,7,7,7
17,27,1297,5,2,1,1850,4,53,3,1,...,3,3,80,0,3,2,5,4,0,2
18,29,574,20,1,1,1852,4,40,3,1,...,3,2,80,0,3,4,11,8,3,10
19,32,1318,10,4,1,1853,4,79,3,2,...,3,3,80,0,2,4,0,0,0,0
20,42,355,10,4,1,1854,3,38,3,1,...,4,2,80,2,1,2,6,3,3,3
21,47,207,9,4,1,1856,2,64,3,1,...,3,3,80,0,2,3,2,2,2,0
22,46,706,2,2,1,1857,4,82,3,3,...,3,3,80,1,4,2,9,8,4,7
23,28,280,1,2,1,1858,3,43,3,1,...,3,2,80,1,2,3,3,2,2,2
24,29,726,29,1,1,1859,4,93,1,2,...,3,4,80,2,3,3,7,0,1,6
25,42,1142,8,3,1,1860,4,81,3,1,...,3,4,80,0,3,3,0,0,0,0
26,32,414,2,4,1,1862,3,82,2,2,...,3,3,80,0,3,2,2,2,2,2
27,46,1319,3,3,1,1863,1,45,4,4,...,3,4,80,1,5,3,19,17,2,8
28,27,728,23,1,1,1864,2,36,2,2,...,4,4,80,1,5,3,9,8,5,8
29,29,352,6,1,1,1865,4,87,2,1,...,3,4,80,0,3,3,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,36,688,4,2,1,2025,4,97,3,2,...,3,2,80,3,3,3,4,2,0,2
141,56,667,1,4,1,2026,3,57,3,2,...,4,1,80,1,2,2,13,12,1,9
142,29,1092,1,4,1,2027,1,36,3,1,...,3,2,80,3,3,4,2,2,2,2
143,42,300,2,3,1,2031,1,56,3,5,...,3,1,80,0,2,2,22,6,4,14
144,56,310,7,2,1,2032,4,72,3,1,...,3,4,80,1,4,1,10,9,9,8
145,41,582,28,4,1,2034,1,60,2,4,...,4,3,80,1,3,3,20,7,0,10
146,34,704,28,3,1,2035,4,95,2,2,...,4,4,80,2,2,3,8,7,1,7
147,36,301,15,4,1,2036,4,88,1,2,...,4,1,80,1,4,2,15,12,11,11
148,41,930,3,3,1,2037,3,57,2,2,...,3,3,80,1,5,3,5,4,0,4
149,32,529,2,3,1,2038,4,78,3,1,...,3,4,80,0,4,3,4,2,1,2
150,35,1146,26,4,1,2040,3,31,3,3,...,3,3,80,0,2,3,9,0,1,7
151,38,345,10,2,1,2041,1,100,3,2,...,3,3,80,1,1,3,10,7,1,9
152,50,878,1,4,1,2044,2,94,3,2,...,3,4,80,2,3,3,6,3,0,1
153,36,1120,11,4,1,2045,2,100,2,2,...,3,1,80,1,2,2,6,3,0,0
154,45,374,20,3,1,2046,4,50,3,2,...,3,3,80,0,3,3,5,3,0,1
155,40,1322,2,4,1,2048,3,52,2,1,...,3,4,80,0,2,3,2,2,2,2
156,35,1199,18,4,1,2049,3,80,3,2,...,3,4,80,2,2,4,10,2,0,2
157,40,1194,2,4,1,2051,3,98,3,1,...,3,2,80,3,2,3,5,3,0,2
158,35,287,1,4,1,2052,3,62,1,1,...,3,4,80,1,5,3,4,3,1,1
159,29,1378,13,2,1,2053,4,46,2,2,...,3,1,80,1,2,3,4,3,0,3
160,29,468,28,4,1,2054,4,73,2,1,...,3,2,80,0,3,1,5,4,0,4
161,50,410,28,3,1,2055,4,39,2,3,...,3,2,80,1,3,3,3,2,2,0
162,39,722,24,1,1,2056,2,60,2,4,...,3,1,80,1,2,2,20,9,9,6
163,31,325,5,3,1,2057,2,74,3,2,...,3,2,80,0,2,3,9,4,1,7
164,26,1167,5,3,1,2060,4,30,2,1,...,3,4,80,0,2,3,4,2,0,0
165,36,884,23,2,1,2061,3,41,4,2,...,3,3,80,1,3,3,5,2,0,3
166,39,613,6,1,1,2062,4,42,2,3,...,3,1,80,1,5,3,7,7,1,7
167,27,155,4,3,1,2064,2,87,4,2,...,4,2,80,1,0,3,6,2,0,3
168,49,1023,2,3,1,2065,4,63,2,2,...,3,4,80,0,3,2,9,6,0,8
169,34,628,8,3,1,2068,2,82,4,2,...,3,1,80,0,3,4,4,3,1,2

In [255]:
#予測する
hr_predict = hr_regressor.predict(X_test)
hr_predict

array([  9.5952381 ,  29.36734694,   5.78787879,  24.89473684,
         9.98857143,  13.83673469,   9.98857143,   3.78431373,
         9.98857143,   4.96      ,  29.36734694,   0.28571429,
         1.04347826,   5.97619048,   9.98857143,  12.8627451 ,
         6.59375   ,   5.78787879,  10.66666667,  12.8627451 ,
         9.67391304,   7.65217391,  13.83673469,   3.78431373,
        12.8627451 ,   7.65217391,   9.98857143,  24.66666667,
         9.5952381 ,   1.04347826,  21.84      ,  24.66666667,
         1.04347826,  13.83673469,   7.72413793,   9.98857143,
        17.        ,   1.04347826,   1.04347826,   1.04347826,
         9.5952381 ,   9.5952381 ,   9.98857143,   5.97619048,
         9.98857143,   4.96      ,   9.5952381 ,   9.5952381 ,
        21.        ,   1.04347826,   9.5952381 ,  24.66666667,
        12.8627451 ,   5.78787879,   3.78431373,   9.98857143,
         9.98857143,  16.44444444,   9.98857143,   9.98857143,
         5.97619048,   7.72413793,   9.98857143,   9.5952381 ,
         6.59375   ,   1.04347826,   9.98857143,   5.78787879,
        15.5       ,  12.8627451 ,  13.83673469,  13.83673469,
         9.5952381 ,  19.7       ,  29.36734694,   5.97619048,
         9.67391304,  24.66666667,  12.8627451 ,   1.04347826,
         4.96      ,   5.78787879,   3.78431373,   5.78787879,
        13.9       ,   9.5952381 ,   7.72413793,   4.96      ,
         9.98857143,   9.5952381 ,   5.97619048,   7.65217391,
         9.5952381 ,   6.59375   ,  12.8627451 ,   9.5952381 ,
        19.41176471,  13.83673469,   9.5952381 ,   9.5952381 ,
         5.78787879,  29.36734694,   1.04347826,  21.        ,
        19.7       ,   9.45454545,  13.83673469,   4.96      ,
         5.78787879,   9.5952381 ,   9.98857143,   4.54545455,
        10.66666667,   5.97619048,  21.5       ,   1.04347826,
        16.875     ,   2.33333333,   9.98857143,   9.98857143,
         9.67391304,  16.44444444,   7.65217391,   3.78431373,
         9.5952381 ,   9.5952381 ,   5.78787879,   7.65217391,
         2.33333333,   9.98857143,  20.        ,  14.33333333,
        13.42857143,   4.96      ,  14.44444444,   7.65217391,
         2.33333333,  17.        ,   1.04347826,   9.5952381 ,
         9.98857143,  16.875     ,   5.97619048,  21.84      ,
        14.44444444,  21.84      ,   9.5952381 ,  17.        ,
         9.98857143,   3.78431373,   9.5952381 ,   9.5952381 ,
        13.83673469,   9.98857143,   9.98857143,   7.65217391,
         9.5952381 ,  17.        ,   3.78431373,   9.98857143,
         5.78787879,  19.41176471,  21.        ,   9.5952381 ,
         3.78431373,   9.98857143,   9.98857143,   6.59375   ,
        13.83673469,   9.98857143])

In [256]:
df_predict = pd.DataFrame(hr_predict)
predict_result = df_predict.rename(columns={0:"Predict_Result"})
predict_result

     Predict_Result
0          9.595238
1         29.367347
2          5.787879
3         24.894737
4          9.988571
5         13.836735
6          9.988571
7          3.784314
8          9.988571
9          4.960000
10        29.367347
11         0.285714
12         1.043478
13         5.976190
14         9.988571
15        12.862745
16         6.593750
17         5.787879
18        10.666667
19        12.862745
20         9.673913
21         7.652174
22        13.836735
23         3.784314
24        12.862745
25         7.652174
26         9.988571
27        24.666667
28         9.595238
29         1.043478
..              ...
140        9.988571
141       16.875000
142        5.976190
143       21.840000
144       14.444444
145       21.840000
146        9.595238
147       17.000000
148        9.988571
149        3.784314
150        9.595238
151        9.595238
152       13.836735
153        9.988571
154        9.988571
155        7.652174
156        9.595238
157       17.000000
158        3.784314
159        9.988571
160        5.787879
161       19.411765
162       21.000000
163        9.595238
164        3.784314
165        9.988571
166        9.988571
167        6.593750
168       13.836735
169        9.988571

[170 rows x 1 columns]

In [257]:
y_totalworkingyears = hr_data_test["TotalWorkingYears"]
y_totalworkingyears = pd.DataFrame(y_totalworkingyears)

In [258]:
#predictの結果とテストデータの平均二乗誤差を求める
#ひろき先生のご指示により、ここでは、あえて平均二乗誤差を求める関数を自前で作成する
compassion_df = pd.concat([y_totalworkingyears, predict_result], axis=1)
compassion_df

     TotalWorkingYears  Predict_Result
0                   10        9.595238
1                   37       29.367347
2                    6        5.787879
3                   28       24.894737
4                   15        9.988571
5                   14       13.836735
6                    9        9.988571
7                    3        3.784314
8                   20        9.988571
9                    5        4.960000
10                  23       29.367347
11                   0        0.285714
12                   2        1.043478
13                   4        5.976190
14                  10        9.988571
15                  15       12.862745
16                   7        6.593750
17                   6        5.787879
18                  11       10.666667
19                   4       12.862745
20                  10        9.673913
21                   7        7.652174
22                  12       13.836735
23                   3        3.784314
24                  11       12.862745
25                   8        7.652174
26                   7        9.988571
27                  25       24.666667
28                   9        9.595238
29                   1        1.043478
..                 ...             ...
140                 18        9.988571
141                 13       16.875000
142                  4        5.976190
143                 24       21.840000
144                 14       14.444444
145                 21       21.840000
146                  8        9.595238
147                 15       17.000000
148                 14        9.988571
149                  4        3.784314
150                  9        9.595238
151                 10        9.595238
152                 12       13.836735
153                  8        9.988571
154                  8        9.988571
155                  8        7.652174
156                 10        9.595238
157                 20       17.000000
158                  4        3.784314
159                 10        9.988571
160                  5        5.787879
161                 20       19.411765
162                 21       21.000000
163                 10        9.595238
164                  5        3.784314
165                 17        9.988571
166                  9        9.988571
167                  6        6.593750
168                 17       13.836735
169                  6        9.988571

[170 rows x 2 columns]

In [259]:
gap = (compassion_df["TotalWorkingYears"] - compassion_df["Predict_Result"])**2
gap

0        0.163832
1       58.257393
2        0.044995
3        9.642659
4       25.114416
5        0.026656
6        0.977273
7        0.615148
8      100.228702
9        0.001600
10      40.543107
11       0.081633
12       0.914934
13       3.905329
14       0.000131
15       4.567859
16       0.165039
17       0.044995
18       0.111111
19      78.548251
20       0.106333
21       0.425331
22       3.373594
23       0.615148
24       3.469819
25       0.120983
26       8.931559
27       0.111111
28       0.354308
29       0.001890
          ...
140     64.182988
141     15.015625
142      3.905329
143      4.665600
144      0.197531
145      0.705600
146      2.544785
147      4.000000
148     16.091559
149      0.046521
150      0.354308
151      0.163832
152      3.373594
153      3.954416
154      3.954416
155      0.120983
156      0.163832
157      9.000000
158      0.046521
159      0.000131
160      0.620753
161      0.346021
162      0.000000
163      0.163832
164      1.477893
165     49.160131
166      0.977273
167      0.352539
168     10.006247
169     15.908702
dtype: float64

In [260]:
gap.mean()

7.53609592120854

In [261]:
math.sqrt(gap.mean())

2.745195060684858